coverage:
  precision: 2
  round: down
  range: "70...100"

ignore:
  - "com.duberton.Application.kt"
  - "com.duberton.adapter.input.api.v1.*.kt"
  - "**/*Config.kt"
  - ".*/config/.*"
  - "**/*Ext.kt"