coverage:
  precision: 2
  round: down
  range: "70...100"

ignore:
  - "**/Application.kt"
  - "**/api/v1/**"
  - "**JobScheduler*"
  - "**ReleasedAlbumsStarter*"
  - "**/*Config.kt"
  - "**/config/**"
  - "**/*Ext.kt"