version: '3.5'

services:
  mongodb:
    image: 'mongo:4.0.26'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: bandcamper
    volumes:
      - ./infrastructure/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bandcamper
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - bandcamper
  localstack:
    image: 'localstack/localstack:0.12.15'
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./infrastructure/localstack:/docker-entrypoint-initaws.d"
    networks:
      - bandcamper
  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.29.1
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus:/etc/prometheus
    networks:
      - observability
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - "3001:3000"
    user: "104"
    networks:
      - observability

networks:
  bandcamper:
    name: bandcamper
    driver: bridge
  observability:
    name: observability
    driver: bridge