{{- if .Values.certs.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager.io
spec:
  acme:
    email: {{ .Values.certs.email }}
    server: {{ .Values.certs.server }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}