apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bandcamper.fullname" . }}
  labels:
    {{- include "bandcamper.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.job.image.pullPolicy }}
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: awsAccessKey
                      name: aws-credentials
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: awsSecretAccess
                      name: aws-credentials
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      key: awsRegion
                      name: aws-credentials   