apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bandcamper.fullname" . }}
  labels:
    {{- include "bandcamper.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bandcamper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bandcamper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bandcamper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_HOST
              value: {{ .Values.env.mongoHost }}
            - name: MONGO_PORT
              value: {{ .Values.env.mongoPort | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.redisHost }}
            - name: REDIS_PORT
              value: {{ .Values.env.redisPort | quote }}
            - name: SES_HOST
              value: {{ .Values.env.sesHost }}
            - name: SES_PORT
              value: {{ .Values.env.sesPort | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.jwtSecret }}
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: googleClientId
                  name: google-credentials
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: googleClientSecret
                  name: google-credentials
            - name: GOOGLE_URL_PROVIDER
              value: {{ .Values.env.urlProvider }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsAccessKey
                  name: aws-credentials
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretAccess
                  name: aws-credentials
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  key: awsRegion
                  name: aws-credentials                         
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
