{
 "title": "bandcamper",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_BANDCAMPER", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of active threads",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  {
   "title": "Number of albums successfully created",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds{route=\"/v1/album/(authenticate \\\"default\\\")\",status=\"201\",quantile=\"0.95\"}",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "Number of albums retrieved successfully by an email",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds{method=\"GET\",route=\"/v1/album/(authenticate \\\"default\\\")\",status=\"200\",quantile=\"0.99\"}",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  }
 ]
}