name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  gradle-validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

  build:
    name: Build app
    runs-on: ubuntu-latest
    needs:
      - gradle-validation

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Setup Gradle Wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./backend/gradlew -b backend/build.gradle.kts installDist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./backend/build/libs
          if-no-files-found: error

      - name: Build and push the docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.sha }}:latest
          push: true


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

      - name: Helm tool installer
        uses: azure/setup-helm@v1
        with:
          token: ${{ secrets.DOCKER_HUB_TOKEN }}