name: Install ArgoCD

on:
  push:
    branches-ignore:
      - '*'
  workflow_dispatch:

jobs:
  install-app:
    name: Install ArgoCD
    runs-on: ubuntu-latest

    steps:

      - name: Installing kubectl
        uses: azure/setup-kubectl@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install aws-cli
        uses: isbang/setup-awscli@v0.1.0

      - name: AWS EKS kube config
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }}}
      
      - name: Creating ArgoCD namespace
        run: kubectl create namespace argocd

      - name: Installing ArgoCD
        run: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Exposing ArgoCD service
        run: | 
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'