name: Continuous integration/delivery/deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-caches-

      - name: Setup Gradle Wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: backend
          wrapper-directory: backend
          arguments: installDist
  
      - name: Upload src
        uses: actions/upload-artifact@v2
        with:
          name: src
          path: backend
          if-no-files-found: error
  
  quality:
    name: Code quality
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download src
        uses: actions/download-artifact@v2
        with:
          name: src

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization=duberton
            -Dsonar.projectKey=bandcamper

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Download src
        uses: actions/download-artifact@v2
        with:
          name: src

      - name: Docker Hub login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Builds and pushes the docker image to docker hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bandcamper:${{ github.sha }}
          push: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checking out sources
        uses: actions/checkout@v2

      - name: Updating Charts appVersion
        uses: mikefarah/yq@v4.6.3
        with:
          cmd: yq eval '.appVersion = "${{ github.sha }}"' -i infrastructure/helm/Chart.yaml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bumping docker image tag to ${{ github.sha }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
